name: 'Get and Cache Dependencies'
description: 'Get dependencies and cache them'
inputs:
  caching:
    description: 'Whether to cache dependencies or not'
    required: false
    # must be string
    default: 'false'
outputs:
  used-cache:
    description: 'Whether cash was used'
    value: steps.log.outputs.cache
runs:
  using: 'composite'
  steps:
    - name: Log
      id: log
      run: echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash
    - name: Log
      run: echo "${{ inputs.caching }}"
      shell: bash
